// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DeviceLog.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_DEVICELOG_H_
#define _FAST_DDS_GENERATED_DEVICELOG_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DeviceLog_SOURCE)
#define DeviceLog_DllAPI __declspec( dllexport )
#else
#define DeviceLog_DllAPI __declspec( dllimport )
#endif // DeviceLog_SOURCE
#else
#define DeviceLog_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DeviceLog_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure DeviceLog defined by the user in the IDL file.
 * @ingroup DEVICELOG
 */
class DeviceLog
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport DeviceLog();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~DeviceLog();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object DeviceLog that will be copied.
     */
    eProsima_user_DllExport DeviceLog(
            const DeviceLog& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object DeviceLog that will be copied.
     */
    eProsima_user_DllExport DeviceLog(
            DeviceLog&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object DeviceLog that will be copied.
     */
    eProsima_user_DllExport DeviceLog& operator =(
            const DeviceLog& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object DeviceLog that will be copied.
     */
    eProsima_user_DllExport DeviceLog& operator =(
            DeviceLog&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x DeviceLog object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const DeviceLog& x) const;

    /*!
     * @brief Comparison operator.
     * @param x DeviceLog object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const DeviceLog& x) const;

    /*!
     * @brief This function copies the value in member device_id
     * @param _device_id New value to be copied in member device_id
     */
    eProsima_user_DllExport void device_id(
            const std::string& _device_id);

    /*!
     * @brief This function moves the value in member device_id
     * @param _device_id New value to be moved in member device_id
     */
    eProsima_user_DllExport void device_id(
            std::string&& _device_id);

    /*!
     * @brief This function returns a constant reference to member device_id
     * @return Constant reference to member device_id
     */
    eProsima_user_DllExport const std::string& device_id() const;

    /*!
     * @brief This function returns a reference to member device_id
     * @return Reference to member device_id
     */
    eProsima_user_DllExport std::string& device_id();
    /*!
     * @brief This function copies the value in member device_type
     * @param _device_type New value to be copied in member device_type
     */
    eProsima_user_DllExport void device_type(
            const std::string& _device_type);

    /*!
     * @brief This function moves the value in member device_type
     * @param _device_type New value to be moved in member device_type
     */
    eProsima_user_DllExport void device_type(
            std::string&& _device_type);

    /*!
     * @brief This function returns a constant reference to member device_type
     * @return Constant reference to member device_type
     */
    eProsima_user_DllExport const std::string& device_type() const;

    /*!
     * @brief This function returns a reference to member device_type
     * @return Reference to member device_type
     */
    eProsima_user_DllExport std::string& device_type();
    /*!
     * @brief This function sets a value in member temperature
     * @param _temperature New value for member temperature
     */
    eProsima_user_DllExport void temperature(
            double _temperature);

    /*!
     * @brief This function returns the value of member temperature
     * @return Value of member temperature
     */
    eProsima_user_DllExport double temperature() const;

    /*!
     * @brief This function returns a reference to member temperature
     * @return Reference to member temperature
     */
    eProsima_user_DllExport double& temperature();

    /*!
     * @brief This function sets a value in member humidity
     * @param _humidity New value for member humidity
     */
    eProsima_user_DllExport void humidity(
            double _humidity);

    /*!
     * @brief This function returns the value of member humidity
     * @return Value of member humidity
     */
    eProsima_user_DllExport double humidity() const;

    /*!
     * @brief This function returns a reference to member humidity
     * @return Reference to member humidity
     */
    eProsima_user_DllExport double& humidity();

    /*!
     * @brief This function sets a value in member co2
     * @param _co2 New value for member co2
     */
    eProsima_user_DllExport void co2(
            int32_t _co2);

    /*!
     * @brief This function returns the value of member co2
     * @return Value of member co2
     */
    eProsima_user_DllExport int32_t co2() const;

    /*!
     * @brief This function returns a reference to member co2
     * @return Reference to member co2
     */
    eProsima_user_DllExport int32_t& co2();

    /*!
     * @brief This function sets a value in member light
     * @param _light New value for member light
     */
    eProsima_user_DllExport void light(
            int32_t _light);

    /*!
     * @brief This function returns the value of member light
     * @return Value of member light
     */
    eProsima_user_DllExport int32_t light() const;

    /*!
     * @brief This function returns a reference to member light
     * @return Reference to member light
     */
    eProsima_user_DllExport int32_t& light();

    /*!
     * @brief This function sets a value in member occupancy
     * @param _occupancy New value for member occupancy
     */
    eProsima_user_DllExport void occupancy(
            bool _occupancy);

    /*!
     * @brief This function returns the value of member occupancy
     * @return Value of member occupancy
     */
    eProsima_user_DllExport bool occupancy() const;

    /*!
     * @brief This function returns a reference to member occupancy
     * @return Reference to member occupancy
     */
    eProsima_user_DllExport bool& occupancy();

    /*!
     * @brief This function sets a value in member battery
     * @param _battery New value for member battery
     */
    eProsima_user_DllExport void battery(
            int32_t _battery);

    /*!
     * @brief This function returns the value of member battery
     * @return Value of member battery
     */
    eProsima_user_DllExport int32_t battery() const;

    /*!
     * @brief This function returns a reference to member battery
     * @return Reference to member battery
     */
    eProsima_user_DllExport int32_t& battery();

    /*!
     * @brief This function sets a value in member signal_strength
     * @param _signal_strength New value for member signal_strength
     */
    eProsima_user_DllExport void signal_strength(
            int32_t _signal_strength);

    /*!
     * @brief This function returns the value of member signal_strength
     * @return Value of member signal_strength
     */
    eProsima_user_DllExport int32_t signal_strength() const;

    /*!
     * @brief This function returns a reference to member signal_strength
     * @return Reference to member signal_strength
     */
    eProsima_user_DllExport int32_t& signal_strength();

    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            double _timestamp);

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport double timestamp() const;

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport double& timestamp();

    /*!
     * @brief This function sets a value in member sequence_number
     * @param _sequence_number New value for member sequence_number
     */
    eProsima_user_DllExport void sequence_number(
            int32_t _sequence_number);

    /*!
     * @brief This function returns the value of member sequence_number
     * @return Value of member sequence_number
     */
    eProsima_user_DllExport int32_t sequence_number() const;

    /*!
     * @brief This function returns a reference to member sequence_number
     * @return Reference to member sequence_number
     */
    eProsima_user_DllExport int32_t& sequence_number();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const DeviceLog& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    std::string m_device_id;
    std::string m_device_type;
    double m_temperature;
    double m_humidity;
    int32_t m_co2;
    int32_t m_light;
    bool m_occupancy;
    int32_t m_battery;
    int32_t m_signal_strength;
    double m_timestamp;
    int32_t m_sequence_number;
};

#endif // _FAST_DDS_GENERATED_DEVICELOG_H_