// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SensorData.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "SensorData.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

SensorData::SensorData()
{
    // m_device_id com.eprosima.idl.parser.typecode.StringTypeCode@18bf3d14
    m_device_id ="";
    // m_sequence_number com.eprosima.idl.parser.typecode.PrimitiveTypeCode@42607a4f
    m_sequence_number = 0;
    // m_timestamp com.eprosima.idl.parser.typecode.PrimitiveTypeCode@782663d3
    m_timestamp = 0;
    // m_temperature com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1990a65e
    m_temperature = 0.0;
    // m_humidity com.eprosima.idl.parser.typecode.PrimitiveTypeCode@64485a47
    m_humidity = 0.0;
    // m_co2 com.eprosima.idl.parser.typecode.PrimitiveTypeCode@25bbf683
    m_co2 = 0.0;
    // m_light com.eprosima.idl.parser.typecode.PrimitiveTypeCode@6ec8211c
    m_light = 0.0;
    // m_occupancy com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7276c8cd
    m_occupancy = false;
    // m_battery com.eprosima.idl.parser.typecode.PrimitiveTypeCode@544a2ea6
    m_battery = 0.0;
    // m_signal_strength com.eprosima.idl.parser.typecode.PrimitiveTypeCode@2e3fc542
    m_signal_strength = 0.0;

}

SensorData::~SensorData()
{









}

SensorData::SensorData(
        const SensorData& x)
{
    m_device_id = x.m_device_id;
    m_sequence_number = x.m_sequence_number;
    m_timestamp = x.m_timestamp;
    m_temperature = x.m_temperature;
    m_humidity = x.m_humidity;
    m_co2 = x.m_co2;
    m_light = x.m_light;
    m_occupancy = x.m_occupancy;
    m_battery = x.m_battery;
    m_signal_strength = x.m_signal_strength;
}

SensorData::SensorData(
        SensorData&& x) noexcept 
{
    m_device_id = std::move(x.m_device_id);
    m_sequence_number = x.m_sequence_number;
    m_timestamp = x.m_timestamp;
    m_temperature = x.m_temperature;
    m_humidity = x.m_humidity;
    m_co2 = x.m_co2;
    m_light = x.m_light;
    m_occupancy = x.m_occupancy;
    m_battery = x.m_battery;
    m_signal_strength = x.m_signal_strength;
}

SensorData& SensorData::operator =(
        const SensorData& x)
{

    m_device_id = x.m_device_id;
    m_sequence_number = x.m_sequence_number;
    m_timestamp = x.m_timestamp;
    m_temperature = x.m_temperature;
    m_humidity = x.m_humidity;
    m_co2 = x.m_co2;
    m_light = x.m_light;
    m_occupancy = x.m_occupancy;
    m_battery = x.m_battery;
    m_signal_strength = x.m_signal_strength;

    return *this;
}

SensorData& SensorData::operator =(
        SensorData&& x) noexcept
{

    m_device_id = std::move(x.m_device_id);
    m_sequence_number = x.m_sequence_number;
    m_timestamp = x.m_timestamp;
    m_temperature = x.m_temperature;
    m_humidity = x.m_humidity;
    m_co2 = x.m_co2;
    m_light = x.m_light;
    m_occupancy = x.m_occupancy;
    m_battery = x.m_battery;
    m_signal_strength = x.m_signal_strength;

    return *this;
}

bool SensorData::operator ==(
        const SensorData& x) const
{

    return (m_device_id == x.m_device_id && m_sequence_number == x.m_sequence_number && m_timestamp == x.m_timestamp && m_temperature == x.m_temperature && m_humidity == x.m_humidity && m_co2 == x.m_co2 && m_light == x.m_light && m_occupancy == x.m_occupancy && m_battery == x.m_battery && m_signal_strength == x.m_signal_strength);
}

bool SensorData::operator !=(
        const SensorData& x) const
{
    return !(*this == x);
}

size_t SensorData::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t SensorData::getCdrSerializedSize(
        const SensorData& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.device_id().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void SensorData::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_device_id.c_str();
    scdr << m_sequence_number;
    scdr << m_timestamp;
    scdr << m_temperature;
    scdr << m_humidity;
    scdr << m_co2;
    scdr << m_light;
    scdr << m_occupancy;
    scdr << m_battery;
    scdr << m_signal_strength;

}

void SensorData::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_device_id;
    dcdr >> m_sequence_number;
    dcdr >> m_timestamp;
    dcdr >> m_temperature;
    dcdr >> m_humidity;
    dcdr >> m_co2;
    dcdr >> m_light;
    dcdr >> m_occupancy;
    dcdr >> m_battery;
    dcdr >> m_signal_strength;
}

/*!
 * @brief This function copies the value in member device_id
 * @param _device_id New value to be copied in member device_id
 */
void SensorData::device_id(
        const std::string& _device_id)
{
    m_device_id = _device_id;
}

/*!
 * @brief This function moves the value in member device_id
 * @param _device_id New value to be moved in member device_id
 */
void SensorData::device_id(
        std::string&& _device_id)
{
    m_device_id = std::move(_device_id);
}

/*!
 * @brief This function returns a constant reference to member device_id
 * @return Constant reference to member device_id
 */
const std::string& SensorData::device_id() const
{
    return m_device_id;
}

/*!
 * @brief This function returns a reference to member device_id
 * @return Reference to member device_id
 */
std::string& SensorData::device_id()
{
    return m_device_id;
}
/*!
 * @brief This function sets a value in member sequence_number
 * @param _sequence_number New value for member sequence_number
 */
void SensorData::sequence_number(
        uint32_t _sequence_number)
{
    m_sequence_number = _sequence_number;
}

/*!
 * @brief This function returns the value of member sequence_number
 * @return Value of member sequence_number
 */
uint32_t SensorData::sequence_number() const
{
    return m_sequence_number;
}

/*!
 * @brief This function returns a reference to member sequence_number
 * @return Reference to member sequence_number
 */
uint32_t& SensorData::sequence_number()
{
    return m_sequence_number;
}

/*!
 * @brief This function sets a value in member timestamp
 * @param _timestamp New value for member timestamp
 */
void SensorData::timestamp(
        uint64_t _timestamp)
{
    m_timestamp = _timestamp;
}

/*!
 * @brief This function returns the value of member timestamp
 * @return Value of member timestamp
 */
uint64_t SensorData::timestamp() const
{
    return m_timestamp;
}

/*!
 * @brief This function returns a reference to member timestamp
 * @return Reference to member timestamp
 */
uint64_t& SensorData::timestamp()
{
    return m_timestamp;
}

/*!
 * @brief This function sets a value in member temperature
 * @param _temperature New value for member temperature
 */
void SensorData::temperature(
        float _temperature)
{
    m_temperature = _temperature;
}

/*!
 * @brief This function returns the value of member temperature
 * @return Value of member temperature
 */
float SensorData::temperature() const
{
    return m_temperature;
}

/*!
 * @brief This function returns a reference to member temperature
 * @return Reference to member temperature
 */
float& SensorData::temperature()
{
    return m_temperature;
}

/*!
 * @brief This function sets a value in member humidity
 * @param _humidity New value for member humidity
 */
void SensorData::humidity(
        float _humidity)
{
    m_humidity = _humidity;
}

/*!
 * @brief This function returns the value of member humidity
 * @return Value of member humidity
 */
float SensorData::humidity() const
{
    return m_humidity;
}

/*!
 * @brief This function returns a reference to member humidity
 * @return Reference to member humidity
 */
float& SensorData::humidity()
{
    return m_humidity;
}

/*!
 * @brief This function sets a value in member co2
 * @param _co2 New value for member co2
 */
void SensorData::co2(
        float _co2)
{
    m_co2 = _co2;
}

/*!
 * @brief This function returns the value of member co2
 * @return Value of member co2
 */
float SensorData::co2() const
{
    return m_co2;
}

/*!
 * @brief This function returns a reference to member co2
 * @return Reference to member co2
 */
float& SensorData::co2()
{
    return m_co2;
}

/*!
 * @brief This function sets a value in member light
 * @param _light New value for member light
 */
void SensorData::light(
        float _light)
{
    m_light = _light;
}

/*!
 * @brief This function returns the value of member light
 * @return Value of member light
 */
float SensorData::light() const
{
    return m_light;
}

/*!
 * @brief This function returns a reference to member light
 * @return Reference to member light
 */
float& SensorData::light()
{
    return m_light;
}

/*!
 * @brief This function sets a value in member occupancy
 * @param _occupancy New value for member occupancy
 */
void SensorData::occupancy(
        bool _occupancy)
{
    m_occupancy = _occupancy;
}

/*!
 * @brief This function returns the value of member occupancy
 * @return Value of member occupancy
 */
bool SensorData::occupancy() const
{
    return m_occupancy;
}

/*!
 * @brief This function returns a reference to member occupancy
 * @return Reference to member occupancy
 */
bool& SensorData::occupancy()
{
    return m_occupancy;
}

/*!
 * @brief This function sets a value in member battery
 * @param _battery New value for member battery
 */
void SensorData::battery(
        float _battery)
{
    m_battery = _battery;
}

/*!
 * @brief This function returns the value of member battery
 * @return Value of member battery
 */
float SensorData::battery() const
{
    return m_battery;
}

/*!
 * @brief This function returns a reference to member battery
 * @return Reference to member battery
 */
float& SensorData::battery()
{
    return m_battery;
}

/*!
 * @brief This function sets a value in member signal_strength
 * @param _signal_strength New value for member signal_strength
 */
void SensorData::signal_strength(
        float _signal_strength)
{
    m_signal_strength = _signal_strength;
}

/*!
 * @brief This function returns the value of member signal_strength
 * @return Value of member signal_strength
 */
float SensorData::signal_strength() const
{
    return m_signal_strength;
}

/*!
 * @brief This function returns a reference to member signal_strength
 * @return Reference to member signal_strength
 */
float& SensorData::signal_strength()
{
    return m_signal_strength;
}


size_t SensorData::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool SensorData::isKeyDefined()
{
    return false;
}

void SensorData::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
              
}
